### PR TITLE
Proposals: Add quick vote

### PR DESCRIPTION
**Pull request by SebastianBor**
1) I added a quick vote button but I kept the old register/vote workflow intact because I'm not sure whether we are still going to need it.
  - Is it always the case that we want to use all our governance tokens to vote? Or rather the quick vote option still should have the slider to choose how many tokens we want to use?
2) Vote confirmation massage says 'Burning your N tokens is an irreversible action." but as I understand you can get your governance tokens back and hence I didn't add that warning to 'Quick Vote' confirmation. Is my understanding correct?

3) I implemented quick vote as chained actions depositSourceTokens() and vote() but I'm not sure if that's correct. Should we rather send it as a single set of instruction within a single transaction or I'm overthinking it? 

4) I implemented the yes/no vote option as an on/off toggle to make it consistent with the existing screen but I think using Yes/No buttons would make a better UX. Please let me know what you think.

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
1. We don’t need slider, old workflow can be removed
2. We shouldn’t say burning. Displaying simple voted successfully is good enough
3. It should be single transaction
4. Buttons will be better, if we have toggle in other places it would be great if you can replace them

**Comment by bhgames** [comment]
Agree with B. What we want is two buttons - Yay or Nay. The user clicks one and sees a single pop up where they Approve and that's it. They don't have to select how many of their tokens they want to use - they automatically use all of them. You have the ability to construct transactions with any number of instructions (though there is a limit to txn size, so you may be forced to do this across many transactions), so you can mix an dmatch here and use the registering and voting in one go. I recommend looking into the signTransactions (with an S) method that I added awhile back that lets you sign multiple transactions at once.

**Comment by SebastianBor** [comment]
I've addressed all the points raised above and have few more questions:

Design: 
1) If we vote all-in do we still need an option to partially withdraw the tokens ( with slider) or we should just always withdraw all?
2) I kept the logic to have Vote button and then decide Yes/No  in the pop-up but I'm thinking I would rather have Yes/No buttons in the main UI instead of this two step process. It would be more like Like/Dislike buttons. What do you think?
3) What labels should we use for voting? Yes/No or maybe the US parliament style Yeah/Nay? Note in the UK parliament it's Aye/No.
4) Change my vote workflow. If we go with 2) we could keep the opposite vote button in the UI to change mind. Would we still need the Vote withdraw button is such a case? I'm not sure how the economy of using the governance tokens works here.

Technical:

5) I created a reusable hook a47b104 to deal with the scenario when state is no longer available in a given context. Where should generic logic like that go? In the common package?

6) In what proposal state a user is allowed to vote? There was a check in the code to allow voting in Draft and Voting state but any attempt to vote in Draft state failed so I restricted it to Voting. Is that correct?
7) I'm getting warnings when sending transactions:

> Transaction references a signature that is unnecessary, only the fee payer and instruction signer accounts should sign a transaction. This behavior is deprecated and will throw an error in the next major version release

   It was not caused by my changes because I was getting them before but should we address the issue?

8) As expected I had to use sendTransactions() because there were too many instructions for a single transaction. Do we need that fine grained instructions? Or maybe we could create something more coarse grained to send less instructions. For example VoteOnPropsoalInstruction?

**Comment by bhgames** [comment]
1. No - good point.
2. Yes, that was what I was thinking with the Yay/Nay buttons on the page.
3. Yeah/Nay is fine.
4. They can use the Refund my tokens button to pull their tokens out and then click Yeah or Nay again.
5. Put it in the hooks folder of the common package.
6. Voting is only allowed in the Voting state.
7. Please investigate this and fix, as you're the chief worker on this project right now. Good catch!
8. Nah this is fine.

**Comment by SebastianBor** [comment]
1) I've addressed all the issues above except the transaction warning which I think we can take out of the scope of this PR. I'll get back to it later. 

2) I distinguished between 'Withdraw My Vote' scenario when user can change his/her mind while the proposal i still being voted on and 'Refund My Tokens' after the proposal is decided. I'm not quite sure why we would need the Refund step though. Can't we just refund the tokens to user once the proposal is decided instead of asking to go the the UI and doing that manually? Why user would like to keep his/her tokens in a decided proposal?

**Comment by bhgames** [comment]
2. Because there's no easy way with a decentralized app to go and give every user back their tokens at the end of a proposal.

**Pull request merged**
