### PR TITLE
minCommunityTokensToCreateGovernance in realmConfigForm

### PR DESCRIPTION
**Pull request by abrzezinski94**

### CODE REVIEW

**Review by acamill — APPROVED** [review]
Thank you!

**Comment by acamill** [comment]
Actually still create an instruction with the min amount of token to create proposal on governance, even if the field is here.

I think it's the same validation error on both the initial Governance realm init and this Instruction

Screenshot 2021-11-22 at 18 32 24

**Comment by acamill** [comment]
I cannot have it to work if I input more that `1000000` (I need 10_000_000_000)

**Comment by SebastianBor** [comment]
It was a tricky use case with large values. It's fixed in https://github.com/solana-labs/oyster/pull/432

**Pull request merged**
